package com.entity;

public class Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.cid
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.cname
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.part
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    private String part;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.cid
     *
     * @return the value of company.cid
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.cid
     *
     * @param cid the value for company.cid
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.cname
     *
     * @return the value of company.cname
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.cname
     *
     * @param cname the value for company.cname
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.part
     *
     * @return the value of company.part
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public String getPart() {
        return part;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.part
     *
     * @param part the value for company.part
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public void setPart(String part) {
        this.part = part == null ? null : part.trim();
    }
}