package com.entity;

public class Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.cid
     *
     * @mbg.generated Wed Dec 13 21:28:46 CST 2017
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.cname
     *
     * @mbg.generated Wed Dec 13 21:28:46 CST 2017
     */
    private String cname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.cid
     *
     * @return the value of company.cid
     *
     * @mbg.generated Wed Dec 13 21:28:46 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.cid
     *
     * @param cid the value for company.cid
     *
     * @mbg.generated Wed Dec 13 21:28:46 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.cname
     *
     * @return the value of company.cname
     *
     * @mbg.generated Wed Dec 13 21:28:46 CST 2017
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.cname
     *
     * @param cname the value for company.cname
     *
     * @mbg.generated Wed Dec 13 21:28:46 CST 2017
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }
}