package com.entity;

public class Cuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuser.id
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuser.ismanager
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    private Integer ismanager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuser.ename
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuser.sex
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuser.age
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuser.intime
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    private String intime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuser.outtime
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    private String outtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuser.img
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuser.phone
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    private Integer phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuser.address
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuser.cid
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuser.part
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    private String part;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuser.id
     *
     * @return the value of cuser.id
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuser.id
     *
     * @param id the value for cuser.id
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuser.ismanager
     *
     * @return the value of cuser.ismanager
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public Integer getIsmanager() {
        return ismanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuser.ismanager
     *
     * @param ismanager the value for cuser.ismanager
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public void setIsmanager(Integer ismanager) {
        this.ismanager = ismanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuser.ename
     *
     * @return the value of cuser.ename
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuser.ename
     *
     * @param ename the value for cuser.ename
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuser.sex
     *
     * @return the value of cuser.sex
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuser.sex
     *
     * @param sex the value for cuser.sex
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuser.age
     *
     * @return the value of cuser.age
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuser.age
     *
     * @param age the value for cuser.age
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuser.intime
     *
     * @return the value of cuser.intime
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public String getIntime() {
        return intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuser.intime
     *
     * @param intime the value for cuser.intime
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public void setIntime(String intime) {
        this.intime = intime == null ? null : intime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuser.outtime
     *
     * @return the value of cuser.outtime
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public String getOuttime() {
        return outtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuser.outtime
     *
     * @param outtime the value for cuser.outtime
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public void setOuttime(String outtime) {
        this.outtime = outtime == null ? null : outtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuser.img
     *
     * @return the value of cuser.img
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuser.img
     *
     * @param img the value for cuser.img
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuser.phone
     *
     * @return the value of cuser.phone
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuser.phone
     *
     * @param phone the value for cuser.phone
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuser.address
     *
     * @return the value of cuser.address
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuser.address
     *
     * @param address the value for cuser.address
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuser.cid
     *
     * @return the value of cuser.cid
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuser.cid
     *
     * @param cid the value for cuser.cid
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuser.part
     *
     * @return the value of cuser.part
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public String getPart() {
        return part;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuser.part
     *
     * @param part the value for cuser.part
     *
     * @mbg.generated Sun Dec 24 11:34:35 CST 2017
     */
    public void setPart(String part) {
        this.part = part == null ? null : part.trim();
    }
}