package com.entity;

public class Damage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damage.id
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damage.gname
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    private String gname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damage.number
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damage.time
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damage.station
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    private String station;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damage.cause
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    private String cause;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damage.cid
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    private Integer cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damage.id
     *
     * @return the value of damage.id
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damage.id
     *
     * @param id the value for damage.id
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damage.gname
     *
     * @return the value of damage.gname
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damage.gname
     *
     * @param gname the value for damage.gname
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public void setGname(String gname) {
        this.gname = gname == null ? null : gname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damage.number
     *
     * @return the value of damage.number
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damage.number
     *
     * @param number the value for damage.number
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damage.time
     *
     * @return the value of damage.time
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damage.time
     *
     * @param time the value for damage.time
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damage.station
     *
     * @return the value of damage.station
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public String getStation() {
        return station;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damage.station
     *
     * @param station the value for damage.station
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public void setStation(String station) {
        this.station = station == null ? null : station.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damage.cause
     *
     * @return the value of damage.cause
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public String getCause() {
        return cause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damage.cause
     *
     * @param cause the value for damage.cause
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public void setCause(String cause) {
        this.cause = cause == null ? null : cause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damage.cid
     *
     * @return the value of damage.cid
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damage.cid
     *
     * @param cid the value for damage.cid
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }
}