package com.entity;

public class Demand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.id
     *
     * @mbg.generated Sat Dec 09 15:11:54 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.gname
     *
     * @mbg.generated Sat Dec 09 15:11:54 CST 2017
     */
    private String gname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.classify
     *
     * @mbg.generated Sat Dec 09 15:11:54 CST 2017
     */
    private String classify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.need
     *
     * @mbg.generated Sat Dec 09 15:11:54 CST 2017
     */
    private Integer need;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.cost
     *
     * @mbg.generated Sat Dec 09 15:11:54 CST 2017
     */
    private Integer cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demand.cid
     *
     * @mbg.generated Sat Dec 09 15:11:54 CST 2017
     */
    private Integer cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.id
     *
     * @return the value of demand.id
     *
     * @mbg.generated Sat Dec 09 15:11:54 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.id
     *
     * @param id the value for demand.id
     *
     * @mbg.generated Sat Dec 09 15:11:54 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.gname
     *
     * @return the value of demand.gname
     *
     * @mbg.generated Sat Dec 09 15:11:54 CST 2017
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.gname
     *
     * @param gname the value for demand.gname
     *
     * @mbg.generated Sat Dec 09 15:11:54 CST 2017
     */
    public void setGname(String gname) {
        this.gname = gname == null ? null : gname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.classify
     *
     * @return the value of demand.classify
     *
     * @mbg.generated Sat Dec 09 15:11:54 CST 2017
     */
    public String getClassify() {
        return classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.classify
     *
     * @param classify the value for demand.classify
     *
     * @mbg.generated Sat Dec 09 15:11:54 CST 2017
     */
    public void setClassify(String classify) {
        this.classify = classify == null ? null : classify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.need
     *
     * @return the value of demand.need
     *
     * @mbg.generated Sat Dec 09 15:11:54 CST 2017
     */
    public Integer getNeed() {
        return need;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.need
     *
     * @param need the value for demand.need
     *
     * @mbg.generated Sat Dec 09 15:11:54 CST 2017
     */
    public void setNeed(Integer need) {
        this.need = need;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.cost
     *
     * @return the value of demand.cost
     *
     * @mbg.generated Sat Dec 09 15:11:54 CST 2017
     */
    public Integer getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.cost
     *
     * @param cost the value for demand.cost
     *
     * @mbg.generated Sat Dec 09 15:11:54 CST 2017
     */
    public void setCost(Integer cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demand.cid
     *
     * @return the value of demand.cid
     *
     * @mbg.generated Sat Dec 09 15:11:54 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demand.cid
     *
     * @param cid the value for demand.cid
     *
     * @mbg.generated Sat Dec 09 15:11:54 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }
}