package com.entity;

public class Gain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gain.id
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gain.gname
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    private String gname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gain.action
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    private Integer action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gain.time
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gain.number
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gain.cid
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    private Integer cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gain.id
     *
     * @return the value of gain.id
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gain.id
     *
     * @param id the value for gain.id
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gain.gname
     *
     * @return the value of gain.gname
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gain.gname
     *
     * @param gname the value for gain.gname
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public void setGname(String gname) {
        this.gname = gname == null ? null : gname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gain.action
     *
     * @return the value of gain.action
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public Integer getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gain.action
     *
     * @param action the value for gain.action
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public void setAction(Integer action) {
        this.action = action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gain.time
     *
     * @return the value of gain.time
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gain.time
     *
     * @param time the value for gain.time
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gain.number
     *
     * @return the value of gain.number
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gain.number
     *
     * @param number the value for gain.number
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gain.cid
     *
     * @return the value of gain.cid
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gain.cid
     *
     * @param cid the value for gain.cid
     *
     * @mbg.generated Sat Dec 09 22:13:48 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }
}