package com.entity;

public class GainGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaingoods.cid
     *
     * @mbg.generated Sun Dec 17 18:59:31 CST 2017
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaingoods.gname
     *
     * @mbg.generated Sun Dec 17 18:59:31 CST 2017
     */
    private String gname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaingoods.number
     *
     * @mbg.generated Sun Dec 17 18:59:31 CST 2017
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaingoods.cid
     *
     * @return the value of gaingoods.cid
     *
     * @mbg.generated Sun Dec 17 18:59:31 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaingoods.cid
     *
     * @param cid the value for gaingoods.cid
     *
     * @mbg.generated Sun Dec 17 18:59:31 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaingoods.gname
     *
     * @return the value of gaingoods.gname
     *
     * @mbg.generated Sun Dec 17 18:59:31 CST 2017
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaingoods.gname
     *
     * @param gname the value for gaingoods.gname
     *
     * @mbg.generated Sun Dec 17 18:59:31 CST 2017
     */
    public void setGname(String gname) {
        this.gname = gname == null ? null : gname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaingoods.number
     *
     * @return the value of gaingoods.number
     *
     * @mbg.generated Sun Dec 17 18:59:31 CST 2017
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaingoods.number
     *
     * @param number the value for gaingoods.number
     *
     * @mbg.generated Sun Dec 17 18:59:31 CST 2017
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}