package com.entity;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.gname
     *
     * @mbg.generated Sat Dec 09 15:37:39 CST 2017
     */
    private String gname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.classify
     *
     * @mbg.generated Sat Dec 09 15:37:39 CST 2017
     */
    private String classify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.cost
     *
     * @mbg.generated Sat Dec 09 15:37:39 CST 2017
     */
    private Double cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.store
     *
     * @mbg.generated Sat Dec 09 15:37:39 CST 2017
     */
    private Integer store;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.total
     *
     * @mbg.generated Sat Dec 09 15:37:39 CST 2017
     */
    private Integer total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.img
     *
     * @mbg.generated Sat Dec 09 15:37:39 CST 2017
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.cid
     *
     * @mbg.generated Sat Dec 09 15:37:39 CST 2017
     */
    private Integer cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.gname
     *
     * @return the value of goods.gname
     *
     * @mbg.generated Sat Dec 09 15:37:39 CST 2017
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.gname
     *
     * @param gname the value for goods.gname
     *
     * @mbg.generated Sat Dec 09 15:37:39 CST 2017
     */
    public void setGname(String gname) {
        this.gname = gname == null ? null : gname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.classify
     *
     * @return the value of goods.classify
     *
     * @mbg.generated Sat Dec 09 15:37:39 CST 2017
     */
    public String getClassify() {
        return classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.classify
     *
     * @param classify the value for goods.classify
     *
     * @mbg.generated Sat Dec 09 15:37:39 CST 2017
     */
    public void setClassify(String classify) {
        this.classify = classify == null ? null : classify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.cost
     *
     * @return the value of goods.cost
     *
     * @mbg.generated Sat Dec 09 15:37:39 CST 2017
     */
    public Double getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.cost
     *
     * @param cost the value for goods.cost
     *
     * @mbg.generated Sat Dec 09 15:37:39 CST 2017
     */
    public void setCost(Double cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.store
     *
     * @return the value of goods.store
     *
     * @mbg.generated Sat Dec 09 15:37:39 CST 2017
     */
    public Integer getStore() {
        return store;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.store
     *
     * @param store the value for goods.store
     *
     * @mbg.generated Sat Dec 09 15:37:39 CST 2017
     */
    public void setStore(Integer store) {
        this.store = store;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.total
     *
     * @return the value of goods.total
     *
     * @mbg.generated Sat Dec 09 15:37:39 CST 2017
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.total
     *
     * @param total the value for goods.total
     *
     * @mbg.generated Sat Dec 09 15:37:39 CST 2017
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.img
     *
     * @return the value of goods.img
     *
     * @mbg.generated Sat Dec 09 15:37:39 CST 2017
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.img
     *
     * @param img the value for goods.img
     *
     * @mbg.generated Sat Dec 09 15:37:39 CST 2017
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.cid
     *
     * @return the value of goods.cid
     *
     * @mbg.generated Sat Dec 09 15:37:39 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.cid
     *
     * @param cid the value for goods.cid
     *
     * @mbg.generated Sat Dec 09 15:37:39 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }
}