package com.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ismanager
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    private Integer ismanager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.age
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.intime
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    private String intime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.outtime
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    private String outtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.img
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    private Integer phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.cid
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.part
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    private String part;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ismanager
     *
     * @return the value of user.ismanager
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public Integer getIsmanager() {
        return ismanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ismanager
     *
     * @param ismanager the value for user.ismanager
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public void setIsmanager(Integer ismanager) {
        this.ismanager = ismanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.age
     *
     * @return the value of user.age
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.age
     *
     * @param age the value for user.age
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.intime
     *
     * @return the value of user.intime
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public String getIntime() {
        return intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.intime
     *
     * @param intime the value for user.intime
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public void setIntime(String intime) {
        this.intime = intime == null ? null : intime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.outtime
     *
     * @return the value of user.outtime
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public String getOuttime() {
        return outtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.outtime
     *
     * @param outtime the value for user.outtime
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public void setOuttime(String outtime) {
        this.outtime = outtime == null ? null : outtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.img
     *
     * @return the value of user.img
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.img
     *
     * @param img the value for user.img
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.cid
     *
     * @return the value of user.cid
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.cid
     *
     * @param cid the value for user.cid
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.part
     *
     * @return the value of user.part
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public String getPart() {
        return part;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.part
     *
     * @param part the value for user.part
     *
     * @mbg.generated Sun Dec 17 18:35:48 CST 2017
     */
    public void setPart(String part) {
        this.part = part == null ? null : part.trim();
    }
}