package com.dao;

import com.entity.Damage;
import com.entity.DamageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DamageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damage
     *
     * @mbg.generated Thu Dec 14 14:58:01 CST 2017
     */
    long countByExample(DamageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damage
     *
     * @mbg.generated Thu Dec 14 14:58:01 CST 2017
     */
    int deleteByExample(DamageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damage
     *
     * @mbg.generated Thu Dec 14 14:58:01 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damage
     *
     * @mbg.generated Thu Dec 14 14:58:01 CST 2017
     */
    int insert(Damage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damage
     *
     * @mbg.generated Thu Dec 14 14:58:01 CST 2017
     */
    int insertSelective(Damage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damage
     *
     * @mbg.generated Thu Dec 14 14:58:01 CST 2017
     */
    List<Damage> selectByExample(DamageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damage
     *
     * @mbg.generated Thu Dec 14 14:58:01 CST 2017
     */
    Damage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damage
     *
     * @mbg.generated Thu Dec 14 14:58:01 CST 2017
     */
    int updateByExampleSelective(@Param("record") Damage record, @Param("example") DamageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damage
     *
     * @mbg.generated Thu Dec 14 14:58:01 CST 2017
     */
    int updateByExample(@Param("record") Damage record, @Param("example") DamageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damage
     *
     * @mbg.generated Thu Dec 14 14:58:01 CST 2017
     */
    int updateByPrimaryKeySelective(Damage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damage
     *
     * @mbg.generated Thu Dec 14 14:58:01 CST 2017
     */
    int updateByPrimaryKey(Damage record);
}