package com.dao;

import com.entity.Demand;
import com.entity.DemandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DemandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demand
     *
     * @mbg.generated Wed Dec 27 18:06:50 CST 2017
     */
    long countByExample(DemandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demand
     *
     * @mbg.generated Wed Dec 27 18:06:50 CST 2017
     */
    int deleteByExample(DemandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demand
     *
     * @mbg.generated Wed Dec 27 18:06:50 CST 2017
     */
    int insert(Demand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demand
     *
     * @mbg.generated Wed Dec 27 18:06:50 CST 2017
     */
    int insertSelective(Demand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demand
     *
     * @mbg.generated Wed Dec 27 18:06:50 CST 2017
     */
    List<Demand> selectByExample(DemandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demand
     *
     * @mbg.generated Wed Dec 27 18:06:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") Demand record, @Param("example") DemandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demand
     *
     * @mbg.generated Wed Dec 27 18:06:50 CST 2017
     */
    int updateByExample(@Param("record") Demand record, @Param("example") DemandExample example);
}