package com.dao;

import com.entity.GainGoods;
import com.entity.GainGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GainGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaingoods
     *
     * @mbg.generated Sun Dec 17 18:59:31 CST 2017
     */
    long countByExample(GainGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaingoods
     *
     * @mbg.generated Sun Dec 17 18:59:31 CST 2017
     */
    int deleteByExample(GainGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaingoods
     *
     * @mbg.generated Sun Dec 17 18:59:31 CST 2017
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaingoods
     *
     * @mbg.generated Sun Dec 17 18:59:31 CST 2017
     */
    int insert(GainGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaingoods
     *
     * @mbg.generated Sun Dec 17 18:59:31 CST 2017
     */
    int insertSelective(GainGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaingoods
     *
     * @mbg.generated Sun Dec 17 18:59:31 CST 2017
     */
    List<GainGoods> selectByExample(GainGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaingoods
     *
     * @mbg.generated Sun Dec 17 18:59:31 CST 2017
     */
    GainGoods selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaingoods
     *
     * @mbg.generated Sun Dec 17 18:59:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") GainGoods record, @Param("example") GainGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaingoods
     *
     * @mbg.generated Sun Dec 17 18:59:31 CST 2017
     */
    int updateByExample(@Param("record") GainGoods record, @Param("example") GainGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaingoods
     *
     * @mbg.generated Sun Dec 17 18:59:31 CST 2017
     */
    int updateByPrimaryKeySelective(GainGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaingoods
     *
     * @mbg.generated Sun Dec 17 18:59:31 CST 2017
     */
    int updateByPrimaryKey(GainGoods record);
}