package com.dao;

import com.entity.Gain;
import com.entity.GainCore;
import com.entity.GainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gain
     *
     * @mbg.generated Mon Jan 08 11:29:55 CST 2018
     */
    long countByExample(GainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gain
     *
     * @mbg.generated Mon Jan 08 11:29:55 CST 2018
     */
    int deleteByExample(GainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gain
     *
     * @mbg.generated Mon Jan 08 11:29:55 CST 2018
     */
    int insert(Gain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gain
     *
     * @mbg.generated Mon Jan 08 11:29:55 CST 2018
     */
    int insertSelective(Gain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gain
     *
     * @mbg.generated Mon Jan 08 11:29:55 CST 2018
     */
    List<Gain> selectByExample(GainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gain
     *
     * @mbg.generated Mon Jan 08 11:29:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") Gain record, @Param("example") GainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gain
     *
     * @mbg.generated Mon Jan 08 11:29:55 CST 2018
     */
    int updateByExample(@Param("record") Gain record, @Param("example") GainExample example);

    void take(@Param("cid") Integer cid, @Param("id") Integer id);

    List<GainCore> gainCore(@Param("cid") Integer cid);

    void returnGoods(@Param("cid") Integer cid, @Param("id") Integer id, @Param("gname") String gname, @Param("number") Integer number);
}